jobs:
  integration-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            # pytest would be a dep in requirements.txt
            robot -d ./robot-out test1.robot
          name: Test
orbs:
  python: circleci/python@0.1
version: 2.1
workflows:
  main:
    jobs:
      - integration-test
