jobs:
  integration-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: mkdir robot-out
      - run:
          command: robot --xunit ./robot-out/result.xml test1.robot
          name: Test
      - store_test_results:
          path: ./robot-out
      - store_artifacts:
          path: ./robot-out
orbs:
  python: circleci/python@0.1
version: 2.1
workflows:
  main:
    jobs:
      - integration-test
